services:
  web:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html  # <--- PINDAH KAT SINI (Sebab ini folder PHP)
    networks:
      - my-network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rahasia123
      MYSQL_DATABASE: belajar_docker
    volumes:
      - ./data_db:/var/lib/mysql  # <--- Kekalkan yang ni (Untuk simpan data DB)
    networks:
      - my-network

networks:
  my-network:
