services:
  # 1. PHP Application
  app:
    image: php:8.2-fpm
    build: .
    restart: always
    ports:
      - "9000:9000"  # Tambah ini jika tiada
    volumes:
      - .:/var/www/html
    networks:
      - my-network

  # 2. Database (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    networks:
      - my-network

  # 3. Web Server (Nginx)
  web:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      # Jika kau ada fail nginx.conf sendiri, un-comment baris bawah:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf # <--- TAMBAH BARIS NI
    networks:
      - my-network

  # 4. Database Management (Adminer)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
